version: "3"

services:
  server: 
    environment: 
      - TZ=America/Toronto
    image: docker.io/chuot/rdio-scanner:latest
    ports:
      - "3000:3000"
    volumes:
      - /home/radio/rdio-scanner:/app/data:z
      - /home/radio/SDRTrunk/recordings:/recordings:z